// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apiserver/apiserver.proto

/*
Package apiserver is a generated protocol buffer package.

It is generated from these files:
	pkg/apiserver/apiserver.proto

It has these top-level messages:
	WorkflowIdentifier
	SearchWorkflowRequest
	SearchWorkflowResponse
	WorkflowInvocationIdentifier
	WorkflowInvocationQuery
	WorkflowInvocationList
	WorkflowInvocationGetReponse
	Health
*/
package apiserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/fission/fission-workflow/pkg/types"
import eventstore "github.com/fission/fission-workflow/pkg/eventstore"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkflowIdentifier struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *WorkflowIdentifier) Reset()                    { *m = WorkflowIdentifier{} }
func (m *WorkflowIdentifier) String() string            { return proto.CompactTextString(m) }
func (*WorkflowIdentifier) ProtoMessage()               {}
func (*WorkflowIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WorkflowIdentifier) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchWorkflowRequest struct {
}

func (m *SearchWorkflowRequest) Reset()                    { *m = SearchWorkflowRequest{} }
func (m *SearchWorkflowRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchWorkflowRequest) ProtoMessage()               {}
func (*SearchWorkflowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SearchWorkflowResponse struct {
	Data []*types.Workflow `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *SearchWorkflowResponse) Reset()                    { *m = SearchWorkflowResponse{} }
func (m *SearchWorkflowResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchWorkflowResponse) ProtoMessage()               {}
func (*SearchWorkflowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchWorkflowResponse) GetData() []*types.Workflow {
	if m != nil {
		return m.Data
	}
	return nil
}

type WorkflowInvocationIdentifier struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *WorkflowInvocationIdentifier) Reset()                    { *m = WorkflowInvocationIdentifier{} }
func (m *WorkflowInvocationIdentifier) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationIdentifier) ProtoMessage()               {}
func (*WorkflowInvocationIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WorkflowInvocationIdentifier) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WorkflowInvocationQuery struct {
	Subject string `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
}

func (m *WorkflowInvocationQuery) Reset()                    { *m = WorkflowInvocationQuery{} }
func (m *WorkflowInvocationQuery) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationQuery) ProtoMessage()               {}
func (*WorkflowInvocationQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WorkflowInvocationQuery) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type WorkflowInvocationList struct {
	Invocations []string `protobuf:"bytes,1,rep,name=invocations" json:"invocations,omitempty"`
}

func (m *WorkflowInvocationList) Reset()                    { *m = WorkflowInvocationList{} }
func (m *WorkflowInvocationList) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationList) ProtoMessage()               {}
func (*WorkflowInvocationList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WorkflowInvocationList) GetInvocations() []string {
	if m != nil {
		return m.Invocations
	}
	return nil
}

type WorkflowInvocationGetReponse struct {
	Events []*eventstore.Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *WorkflowInvocationGetReponse) Reset()                    { *m = WorkflowInvocationGetReponse{} }
func (m *WorkflowInvocationGetReponse) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationGetReponse) ProtoMessage()               {}
func (*WorkflowInvocationGetReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WorkflowInvocationGetReponse) GetEvents() []*eventstore.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Health struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *Health) Reset()                    { *m = Health{} }
func (m *Health) String() string            { return proto.CompactTextString(m) }
func (*Health) ProtoMessage()               {}
func (*Health) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Health) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkflowIdentifier)(nil), "apiserver.WorkflowIdentifier")
	proto.RegisterType((*SearchWorkflowRequest)(nil), "apiserver.SearchWorkflowRequest")
	proto.RegisterType((*SearchWorkflowResponse)(nil), "apiserver.SearchWorkflowResponse")
	proto.RegisterType((*WorkflowInvocationIdentifier)(nil), "apiserver.WorkflowInvocationIdentifier")
	proto.RegisterType((*WorkflowInvocationQuery)(nil), "apiserver.WorkflowInvocationQuery")
	proto.RegisterType((*WorkflowInvocationList)(nil), "apiserver.WorkflowInvocationList")
	proto.RegisterType((*WorkflowInvocationGetReponse)(nil), "apiserver.WorkflowInvocationGetReponse")
	proto.RegisterType((*Health)(nil), "apiserver.Health")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WorkflowAPI service

type WorkflowAPIClient interface {
	Create(ctx context.Context, in *types.Workflow, opts ...grpc.CallOption) (*types.Workflow, error)
	Get(ctx context.Context, in *WorkflowIdentifier, opts ...grpc.CallOption) (*types.Workflow, error)
	Search(ctx context.Context, in *SearchWorkflowRequest, opts ...grpc.CallOption) (*SearchWorkflowResponse, error)
}

type workflowAPIClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowAPIClient(cc *grpc.ClientConn) WorkflowAPIClient {
	return &workflowAPIClient{cc}
}

func (c *workflowAPIClient) Create(ctx context.Context, in *types.Workflow, opts ...grpc.CallOption) (*types.Workflow, error) {
	out := new(types.Workflow)
	err := grpc.Invoke(ctx, "/apiserver.WorkflowAPI/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIClient) Get(ctx context.Context, in *WorkflowIdentifier, opts ...grpc.CallOption) (*types.Workflow, error) {
	out := new(types.Workflow)
	err := grpc.Invoke(ctx, "/apiserver.WorkflowAPI/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIClient) Search(ctx context.Context, in *SearchWorkflowRequest, opts ...grpc.CallOption) (*SearchWorkflowResponse, error) {
	out := new(SearchWorkflowResponse)
	err := grpc.Invoke(ctx, "/apiserver.WorkflowAPI/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkflowAPI service

type WorkflowAPIServer interface {
	Create(context.Context, *types.Workflow) (*types.Workflow, error)
	Get(context.Context, *WorkflowIdentifier) (*types.Workflow, error)
	Search(context.Context, *SearchWorkflowRequest) (*SearchWorkflowResponse, error)
}

func RegisterWorkflowAPIServer(s *grpc.Server, srv WorkflowAPIServer) {
	s.RegisterService(&_WorkflowAPI_serviceDesc, srv)
}

func _WorkflowAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Workflow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.WorkflowAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAPIServer).Create(ctx, req.(*types.Workflow))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAPI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAPIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.WorkflowAPI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAPIServer).Get(ctx, req.(*WorkflowIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAPI_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAPIServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.WorkflowAPI/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAPIServer).Search(ctx, req.(*SearchWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiserver.WorkflowAPI",
	HandlerType: (*WorkflowAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _WorkflowAPI_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WorkflowAPI_Get_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _WorkflowAPI_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apiserver.proto",
}

// Client API for WorkflowInvocationAPI service

type WorkflowInvocationAPIClient interface {
	// Create a new workflow invocation
	//
	// In case the invocation specification is missing fields or contains invalid fields, a HTTP 400 is returned.
	Invoke(ctx context.Context, in *types.WorkflowInvocationSpec, opts ...grpc.CallOption) (*WorkflowInvocationIdentifier, error)
	// Cancel a workflow invocation
	//
	// This action is irreverisble. A canceled invocation cannot be resumed or restarted.
	// In case that an invocation already is canceled, has failed or has completed, nothing happens.
	// In case that an invocation does not exist a HTTP 404 error status is returned.
	Cancel(ctx context.Context, in *WorkflowInvocationIdentifier, opts ...grpc.CallOption) (*types.Empty, error)
	// Get the specification and status of a workflow invocation
	//
	// Get returns three different aspects of the workflow invocation, namely the spec (specification), status and logs.
	// To lighten the request load, consider using a more specific request.
	Get(ctx context.Context, in *WorkflowInvocationIdentifier, opts ...grpc.CallOption) (*WorkflowInvocationGetReponse, error)
	// Search for workflow invocations based on a query
	//
	// By default the search returns at most 10 workflow invocations in no specific order.
	Search(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*WorkflowInvocationList, error)
}

type workflowInvocationAPIClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowInvocationAPIClient(cc *grpc.ClientConn) WorkflowInvocationAPIClient {
	return &workflowInvocationAPIClient{cc}
}

func (c *workflowInvocationAPIClient) Invoke(ctx context.Context, in *types.WorkflowInvocationSpec, opts ...grpc.CallOption) (*WorkflowInvocationIdentifier, error) {
	out := new(WorkflowInvocationIdentifier)
	err := grpc.Invoke(ctx, "/apiserver.WorkflowInvocationAPI/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowInvocationAPIClient) Cancel(ctx context.Context, in *WorkflowInvocationIdentifier, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := grpc.Invoke(ctx, "/apiserver.WorkflowInvocationAPI/Cancel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowInvocationAPIClient) Get(ctx context.Context, in *WorkflowInvocationIdentifier, opts ...grpc.CallOption) (*WorkflowInvocationGetReponse, error) {
	out := new(WorkflowInvocationGetReponse)
	err := grpc.Invoke(ctx, "/apiserver.WorkflowInvocationAPI/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowInvocationAPIClient) Search(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*WorkflowInvocationList, error) {
	out := new(WorkflowInvocationList)
	err := grpc.Invoke(ctx, "/apiserver.WorkflowInvocationAPI/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkflowInvocationAPI service

type WorkflowInvocationAPIServer interface {
	// Create a new workflow invocation
	//
	// In case the invocation specification is missing fields or contains invalid fields, a HTTP 400 is returned.
	Invoke(context.Context, *types.WorkflowInvocationSpec) (*WorkflowInvocationIdentifier, error)
	// Cancel a workflow invocation
	//
	// This action is irreverisble. A canceled invocation cannot be resumed or restarted.
	// In case that an invocation already is canceled, has failed or has completed, nothing happens.
	// In case that an invocation does not exist a HTTP 404 error status is returned.
	Cancel(context.Context, *WorkflowInvocationIdentifier) (*types.Empty, error)
	// Get the specification and status of a workflow invocation
	//
	// Get returns three different aspects of the workflow invocation, namely the spec (specification), status and logs.
	// To lighten the request load, consider using a more specific request.
	Get(context.Context, *WorkflowInvocationIdentifier) (*WorkflowInvocationGetReponse, error)
	// Search for workflow invocations based on a query
	//
	// By default the search returns at most 10 workflow invocations in no specific order.
	Search(context.Context, *types.Empty) (*WorkflowInvocationList, error)
}

func RegisterWorkflowInvocationAPIServer(s *grpc.Server, srv WorkflowInvocationAPIServer) {
	s.RegisterService(&_WorkflowInvocationAPI_serviceDesc, srv)
}

func _WorkflowInvocationAPI_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.WorkflowInvocationSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowInvocationAPIServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.WorkflowInvocationAPI/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowInvocationAPIServer).Invoke(ctx, req.(*types.WorkflowInvocationSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowInvocationAPI_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowInvocationIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowInvocationAPIServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.WorkflowInvocationAPI/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowInvocationAPIServer).Cancel(ctx, req.(*WorkflowInvocationIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowInvocationAPI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowInvocationIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowInvocationAPIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.WorkflowInvocationAPI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowInvocationAPIServer).Get(ctx, req.(*WorkflowInvocationIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowInvocationAPI_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowInvocationAPIServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.WorkflowInvocationAPI/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowInvocationAPIServer).Search(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowInvocationAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiserver.WorkflowInvocationAPI",
	HandlerType: (*WorkflowInvocationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _WorkflowInvocationAPI_Invoke_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _WorkflowInvocationAPI_Cancel_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WorkflowInvocationAPI_Get_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _WorkflowInvocationAPI_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apiserver.proto",
}

// Client API for AdminAPI service

type AdminAPIClient interface {
	Status(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*Health, error)
}

type adminAPIClient struct {
	cc *grpc.ClientConn
}

func NewAdminAPIClient(cc *grpc.ClientConn) AdminAPIClient {
	return &adminAPIClient{cc}
}

func (c *adminAPIClient) Status(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*Health, error) {
	out := new(Health)
	err := grpc.Invoke(ctx, "/apiserver.AdminAPI/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminAPI service

type AdminAPIServer interface {
	Status(context.Context, *types.Empty) (*Health, error)
}

func RegisterAdminAPIServer(s *grpc.Server, srv AdminAPIServer) {
	s.RegisterService(&_AdminAPI_serviceDesc, srv)
}

func _AdminAPI_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.AdminAPI/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).Status(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiserver.AdminAPI",
	HandlerType: (*AdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _AdminAPI_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apiserver.proto",
}

// Client API for FissionEnvironmentProxy service

type FissionEnvironmentProxyClient interface {
	Specialize(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error)
	Invoke(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error)
}

type fissionEnvironmentProxyClient struct {
	cc *grpc.ClientConn
}

func NewFissionEnvironmentProxyClient(cc *grpc.ClientConn) FissionEnvironmentProxyClient {
	return &fissionEnvironmentProxyClient{cc}
}

func (c *fissionEnvironmentProxyClient) Specialize(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := grpc.Invoke(ctx, "/apiserver.FissionEnvironmentProxy/Specialize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fissionEnvironmentProxyClient) Invoke(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := grpc.Invoke(ctx, "/apiserver.FissionEnvironmentProxy/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FissionEnvironmentProxy service

type FissionEnvironmentProxyServer interface {
	Specialize(context.Context, *types.Empty) (*types.Empty, error)
	Invoke(context.Context, *types.Empty) (*types.Empty, error)
}

func RegisterFissionEnvironmentProxyServer(s *grpc.Server, srv FissionEnvironmentProxyServer) {
	s.RegisterService(&_FissionEnvironmentProxy_serviceDesc, srv)
}

func _FissionEnvironmentProxy_Specialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FissionEnvironmentProxyServer).Specialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.FissionEnvironmentProxy/Specialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FissionEnvironmentProxyServer).Specialize(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FissionEnvironmentProxy_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FissionEnvironmentProxyServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserver.FissionEnvironmentProxy/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FissionEnvironmentProxyServer).Invoke(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FissionEnvironmentProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiserver.FissionEnvironmentProxy",
	HandlerType: (*FissionEnvironmentProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Specialize",
			Handler:    _FissionEnvironmentProxy_Specialize_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _FissionEnvironmentProxy_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apiserver.proto",
}

func init() { proto.RegisterFile("pkg/apiserver/apiserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x6f, 0x12, 0x5f,
	0x14, 0xfd, 0x01, 0xbf, 0x4c, 0x3b, 0x97, 0x88, 0xed, 0xd3, 0x02, 0x99, 0x14, 0x83, 0x2f, 0x26,
	0x36, 0x4d, 0x9c, 0x89, 0xd4, 0xc4, 0xd8, 0x85, 0xb1, 0x21, 0x48, 0x9b, 0xb8, 0xa8, 0xb0, 0x70,
	0xeb, 0x30, 0x73, 0x81, 0x27, 0xf0, 0xde, 0x74, 0xde, 0x83, 0x8a, 0xc6, 0x8d, 0x7b, 0x57, 0x7e,
	0x34, 0xbf, 0x82, 0x6b, 0x3f, 0x83, 0x99, 0xff, 0x63, 0x87, 0x10, 0x36, 0xf0, 0xde, 0x9d, 0x33,
	0xe7, 0x9e, 0x7b, 0xcf, 0xc9, 0x40, 0xcb, 0x9b, 0x4d, 0x2c, 0xdb, 0x63, 0x12, 0xfd, 0x15, 0xfa,
	0xd9, 0xc9, 0xf4, 0x7c, 0xa1, 0x04, 0xd1, 0xd3, 0x82, 0xf1, 0x6a, 0xc2, 0xd4, 0x74, 0x39, 0x32,
	0x1d, 0xb1, 0xb0, 0xc6, 0x4c, 0x4a, 0x26, 0x78, 0xf2, 0xff, 0xec, 0x56, 0xf8, 0xb3, 0xf1, 0x5c,
	0xdc, 0x5a, 0x01, 0x9b, 0x5a, 0x7b, 0x28, 0xa3, 0xdf, 0x88, 0xc5, 0xe8, 0xee, 0xfa, 0x2a, 0xae,
	0x90, 0x2b, 0xa9, 0x84, 0x8f, 0xb9, 0x63, 0x4c, 0x72, 0x3c, 0x11, 0x62, 0x32, 0xc7, 0x40, 0xa2,
	0x65, 0x73, 0x2e, 0x94, 0xad, 0x98, 0xe0, 0x71, 0x0b, 0xfa, 0x04, 0xc8, 0x87, 0x98, 0xe9, 0xca,
	0x45, 0xae, 0xd8, 0x98, 0xa1, 0x4f, 0x6a, 0x50, 0x66, 0x6e, 0xb3, 0xd4, 0x2e, 0x9d, 0xe8, 0x83,
	0x32, 0x73, 0x69, 0x03, 0x8e, 0x86, 0x68, 0xfb, 0xce, 0x34, 0xc1, 0x0e, 0xf0, 0x66, 0x89, 0x52,
	0xd1, 0x97, 0x50, 0xbf, 0xfb, 0x40, 0x7a, 0x82, 0x4b, 0x24, 0x2d, 0xf8, 0xdf, 0xb5, 0x95, 0xdd,
	0x2c, 0xb5, 0x2b, 0x27, 0xd5, 0x8e, 0x6e, 0xa6, 0x80, 0xb0, 0x4c, 0x4d, 0x38, 0x4e, 0xfb, 0xf2,
	0x95, 0x70, 0x42, 0x51, 0x5b, 0x14, 0x9c, 0x41, 0xa3, 0x88, 0x7f, 0xbf, 0x44, 0x7f, 0x4d, 0x9a,
	0xb0, 0x27, 0x97, 0xa3, 0x4f, 0xe8, 0xa8, 0x18, 0x9f, 0x5c, 0xe9, 0x39, 0xd4, 0x8b, 0x2f, 0xbd,
	0x63, 0x52, 0x91, 0x36, 0x54, 0x59, 0x5a, 0x91, 0xa1, 0x48, 0x7d, 0x90, 0x2f, 0xd1, 0xd7, 0x9b,
	0x04, 0xf6, 0x51, 0x0d, 0x30, 0x9a, 0xef, 0x11, 0x68, 0xd1, 0xaa, 0xe3, 0x09, 0x35, 0xb3, 0x17,
	0x5c, 0x07, 0x71, 0x95, 0xb6, 0x41, 0xbb, 0x44, 0x7b, 0xae, 0xa6, 0xa4, 0x0e, 0x9a, 0x54, 0xb6,
	0x5a, 0xca, 0x58, 0x5e, 0x7c, 0xeb, 0xfc, 0x29, 0x41, 0x35, 0x69, 0x71, 0x71, 0x7d, 0x45, 0x5e,
	0x80, 0xd6, 0xf5, 0xd1, 0x56, 0x48, 0xb2, 0x6d, 0x19, 0xd9, 0x91, 0x3e, 0xfc, 0xfe, 0xeb, 0xf7,
	0xcf, 0x72, 0x8d, 0xea, 0x56, 0xe2, 0xfd, 0x79, 0xe9, 0x94, 0xf4, 0xa1, 0xd2, 0x47, 0x45, 0x5a,
	0x66, 0x16, 0xc1, 0xa2, 0xa1, 0x79, 0x9a, 0x7a, 0x48, 0x73, 0x40, 0x6a, 0x29, 0x8d, 0xf5, 0x95,
	0xb9, 0xdf, 0xc8, 0x47, 0xd0, 0x22, 0x2b, 0x49, 0x3b, 0xc7, 0xb5, 0xd1, 0x76, 0xe3, 0xf1, 0x16,
	0x44, 0xe4, 0x3f, 0x3d, 0x0c, 0xdb, 0x54, 0x49, 0xa6, 0xb6, 0xf3, 0xa3, 0x02, 0x47, 0xc5, 0x9d,
	0x06, 0xa3, 0x8f, 0x40, 0x0b, 0x0a, 0x33, 0x24, 0x0d, 0xb3, 0x88, 0x18, 0x7a, 0xe8, 0x18, 0x4f,
	0x37, 0x0d, 0xb8, 0x21, 0x39, 0xc9, 0x7c, 0xb4, 0x6a, 0x65, 0x76, 0x06, 0x8b, 0x1a, 0x82, 0xd6,
	0xb5, 0xb9, 0x83, 0x73, 0xb2, 0x2b, 0x95, 0xa1, 0x99, 0xbd, 0x85, 0xa7, 0xd6, 0xb4, 0x19, 0x52,
	0x92, 0xd3, 0x83, 0x1c, 0x65, 0xb4, 0xb4, 0x9b, 0x68, 0xfb, 0x3b, 0x33, 0x6e, 0x07, 0x66, 0xf1,
	0x4a, 0x5a, 0x92, 0x62, 0xcb, 0xcb, 0xd4, 0xa7, 0x58, 0xde, 0x3f, 0x6e, 0x6c, 0xce, 0x3b, 0x7d,
	0x10, 0xd2, 0xdd, 0x23, 0xf9, 0xa5, 0x74, 0xde, 0xc0, 0xfe, 0x85, 0xbb, 0x60, 0x3c, 0x0e, 0xdf,
	0x30, 0x8c, 0x65, 0xca, 0x7a, 0x98, 0x63, 0x8d, 0x92, 0x4c, 0xef, 0x87, 0x2c, 0x3a, 0xd9, 0xb3,
	0xe2, 0x08, 0x7b, 0xd0, 0x78, 0x1b, 0x7d, 0x8f, 0x7a, 0x7c, 0xc5, 0x7c, 0xc1, 0x17, 0xc8, 0xd5,
	0xb5, 0x2f, 0x3e, 0xaf, 0xc9, 0x73, 0x80, 0xc0, 0x37, 0x66, 0xcf, 0xd9, 0x17, 0x4c, 0x49, 0x93,
	0x8d, 0x66, 0x7a, 0x64, 0x06, 0xa2, 0x69, 0x0a, 0xee, 0xc2, 0xf7, 0x43, 0x78, 0x99, 0xfc, 0x37,
	0xd2, 0xc2, 0xcf, 0xd6, 0xd9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xdb, 0xab, 0x54, 0x80,
	0x05, 0x00, 0x00,
}
