package workflow_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewList0Params creates a new List0Params object
// with the default values initialized.
func NewList0Params() *List0Params {

	return &List0Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewList0ParamsWithTimeout creates a new List0Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewList0ParamsWithTimeout(timeout time.Duration) *List0Params {

	return &List0Params{

		timeout: timeout,
	}
}

// NewList0ParamsWithContext creates a new List0Params object
// with the default values initialized, and the ability to set a context for a request
func NewList0ParamsWithContext(ctx context.Context) *List0Params {

	return &List0Params{

		Context: ctx,
	}
}

/*List0Params contains all the parameters to send to the API endpoint
for the list 0 operation typically these are written to a http.Request
*/
type List0Params struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the list 0 params
func (o *List0Params) WithTimeout(timeout time.Duration) *List0Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list 0 params
func (o *List0Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list 0 params
func (o *List0Params) WithContext(ctx context.Context) *List0Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list 0 params
func (o *List0Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *List0Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
