// Code generated by go-swagger; DO NOT EDIT.

package workflow_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWfGetParams creates a new WfGetParams object
// with the default values initialized.
func NewWfGetParams() *WfGetParams {
	var ()
	return &WfGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWfGetParamsWithTimeout creates a new WfGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWfGetParamsWithTimeout(timeout time.Duration) *WfGetParams {
	var ()
	return &WfGetParams{

		timeout: timeout,
	}
}

// NewWfGetParamsWithContext creates a new WfGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewWfGetParamsWithContext(ctx context.Context) *WfGetParams {
	var ()
	return &WfGetParams{

		Context: ctx,
	}
}

// NewWfGetParamsWithHTTPClient creates a new WfGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWfGetParamsWithHTTPClient(client *http.Client) *WfGetParams {
	var ()
	return &WfGetParams{
		HTTPClient: client,
	}
}

/*WfGetParams contains all the parameters to send to the API endpoint
for the wf get operation typically these are written to a http.Request
*/
type WfGetParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the wf get params
func (o *WfGetParams) WithTimeout(timeout time.Duration) *WfGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the wf get params
func (o *WfGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the wf get params
func (o *WfGetParams) WithContext(ctx context.Context) *WfGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the wf get params
func (o *WfGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the wf get params
func (o *WfGetParams) WithHTTPClient(client *http.Client) *WfGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the wf get params
func (o *WfGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the wf get params
func (o *WfGetParams) WithID(id string) *WfGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the wf get params
func (o *WfGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *WfGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
