// Code generated by go-swagger; DO NOT EDIT.

package workflow_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// WfListReader is a Reader for the WfList structure.
type WfListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WfListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWfListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWfListOK creates a WfListOK with default headers values
func NewWfListOK() *WfListOK {
	return &WfListOK{}
}

/*WfListOK handles this case with default header values.

WfListOK wf list o k
*/
type WfListOK struct {
	Payload *models.ApiserverSearchWorkflowResponse
}

func (o *WfListOK) Error() string {
	return fmt.Sprintf("[GET /workflow][%d] wfListOK  %+v", 200, o.Payload)
}

func (o *WfListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverSearchWorkflowResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
