// Code generated by go-swagger; DO NOT EDIT.

package workflow_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// NewWfValidateParams creates a new WfValidateParams object
// with the default values initialized.
func NewWfValidateParams() *WfValidateParams {
	var ()
	return &WfValidateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWfValidateParamsWithTimeout creates a new WfValidateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWfValidateParamsWithTimeout(timeout time.Duration) *WfValidateParams {
	var ()
	return &WfValidateParams{

		timeout: timeout,
	}
}

// NewWfValidateParamsWithContext creates a new WfValidateParams object
// with the default values initialized, and the ability to set a context for a request
func NewWfValidateParamsWithContext(ctx context.Context) *WfValidateParams {
	var ()
	return &WfValidateParams{

		Context: ctx,
	}
}

// NewWfValidateParamsWithHTTPClient creates a new WfValidateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWfValidateParamsWithHTTPClient(client *http.Client) *WfValidateParams {
	var ()
	return &WfValidateParams{
		HTTPClient: client,
	}
}

/*WfValidateParams contains all the parameters to send to the API endpoint
for the wf validate operation typically these are written to a http.Request
*/
type WfValidateParams struct {

	/*Body*/
	Body *models.WorkflowSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the wf validate params
func (o *WfValidateParams) WithTimeout(timeout time.Duration) *WfValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the wf validate params
func (o *WfValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the wf validate params
func (o *WfValidateParams) WithContext(ctx context.Context) *WfValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the wf validate params
func (o *WfValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the wf validate params
func (o *WfValidateParams) WithHTTPClient(client *http.Client) *WfValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the wf validate params
func (o *WfValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the wf validate params
func (o *WfValidateParams) WithBody(body *models.WorkflowSpec) *WfValidateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the wf validate params
func (o *WfValidateParams) SetBody(body *models.WorkflowSpec) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *WfValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
