// Code generated by go-swagger; DO NOT EDIT.

package workflow_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// WfValidateReader is a Reader for the WfValidate structure.
type WfValidateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WfValidateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWfValidateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWfValidateOK creates a WfValidateOK with default headers values
func NewWfValidateOK() *WfValidateOK {
	return &WfValidateOK{}
}

/*WfValidateOK handles this case with default header values.

WfValidateOK wf validate o k
*/
type WfValidateOK struct {
	Payload models.ProtobufEmpty
}

func (o *WfValidateOK) Error() string {
	return fmt.Sprintf("[POST /workflow/validate][%d] wfValidateOK  %+v", 200, o.Payload)
}

func (o *WfValidateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
