// Code generated by go-swagger; DO NOT EDIT.

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// HaltReader is a Reader for the Halt structure.
type HaltReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HaltReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewHaltOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewHaltOK creates a HaltOK with default headers values
func NewHaltOK() *HaltOK {
	return &HaltOK{}
}

/*HaltOK handles this case with default header values.

HaltOK halt o k
*/
type HaltOK struct {
	Payload models.ProtobufEmpty
}

func (o *HaltOK) Error() string {
	return fmt.Sprintf("[GET /halt][%d] haltOK  %+v", 200, o.Payload)
}

func (o *HaltOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
