// Code generated by go-swagger; DO NOT EDIT.

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// ResumeReader is a Reader for the Resume structure.
type ResumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewResumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewResumeOK creates a ResumeOK with default headers values
func NewResumeOK() *ResumeOK {
	return &ResumeOK{}
}

/*ResumeOK handles this case with default header values.

ResumeOK resume o k
*/
type ResumeOK struct {
	Payload models.ProtobufEmpty
}

func (o *ResumeOK) Error() string {
	return fmt.Sprintf("[GET /resume][%d] resumeOK  %+v", 200, o.Payload)
}

func (o *ResumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
