// Code generated by go-swagger; DO NOT EDIT.

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewResumeParams creates a new ResumeParams object
// with the default values initialized.
func NewResumeParams() *ResumeParams {

	return &ResumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResumeParamsWithTimeout creates a new ResumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResumeParamsWithTimeout(timeout time.Duration) *ResumeParams {

	return &ResumeParams{

		timeout: timeout,
	}
}

// NewResumeParamsWithContext creates a new ResumeParams object
// with the default values initialized, and the ability to set a context for a request
func NewResumeParamsWithContext(ctx context.Context) *ResumeParams {

	return &ResumeParams{

		Context: ctx,
	}
}

// NewResumeParamsWithHTTPClient creates a new ResumeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResumeParamsWithHTTPClient(client *http.Client) *ResumeParams {

	return &ResumeParams{
		HTTPClient: client,
	}
}

/*ResumeParams contains all the parameters to send to the API endpoint
for the resume operation typically these are written to a http.Request
*/
type ResumeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the resume params
func (o *ResumeParams) WithTimeout(timeout time.Duration) *ResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resume params
func (o *ResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resume params
func (o *ResumeParams) WithContext(ctx context.Context) *ResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resume params
func (o *ResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resume params
func (o *ResumeParams) WithHTTPClient(client *http.Client) *ResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resume params
func (o *ResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
