// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/fes/fes.proto

/*
Package fes is a generated protocol buffer package.

It is generated from these files:
	pkg/fes/fes.proto

It has these top-level messages:
	Aggregate
	Event
	EventHints
	DummyEvent
*/
package fes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Aggregate struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *Aggregate) Reset()                    { *m = Aggregate{} }
func (m *Aggregate) String() string            { return proto.CompactTextString(m) }
func (*Aggregate) ProtoMessage()               {}
func (*Aggregate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Aggregate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Aggregate) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Event struct {
	Id        string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type      string                     `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Aggregate *Aggregate                 `protobuf:"bytes,3,opt,name=aggregate" json:"aggregate,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Data      *google_protobuf1.Any      `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	Parent    *Aggregate                 `protobuf:"bytes,6,opt,name=parent" json:"parent,omitempty"`
	Hints     *EventHints                `protobuf:"bytes,7,opt,name=hints" json:"hints,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetAggregate() *Aggregate {
	if m != nil {
		return m.Aggregate
	}
	return nil
}

func (m *Event) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetData() *google_protobuf1.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetParent() *Aggregate {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Event) GetHints() *EventHints {
	if m != nil {
		return m.Hints
	}
	return nil
}

// EventHints is a collection of optional metadata that help components in the event store to improve performance.
type EventHints struct {
	Completed bool `protobuf:"varint,1,opt,name=completed" json:"completed,omitempty"`
}

func (m *EventHints) Reset()                    { *m = EventHints{} }
func (m *EventHints) String() string            { return proto.CompactTextString(m) }
func (*EventHints) ProtoMessage()               {}
func (*EventHints) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EventHints) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type DummyEvent struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *DummyEvent) Reset()                    { *m = DummyEvent{} }
func (m *DummyEvent) String() string            { return proto.CompactTextString(m) }
func (*DummyEvent) ProtoMessage()               {}
func (*DummyEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DummyEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Aggregate)(nil), "fission.workflows.eventstore.Aggregate")
	proto.RegisterType((*Event)(nil), "fission.workflows.eventstore.Event")
	proto.RegisterType((*EventHints)(nil), "fission.workflows.eventstore.EventHints")
	proto.RegisterType((*DummyEvent)(nil), "fission.workflows.eventstore.DummyEvent")
}

func init() { proto.RegisterFile("pkg/fes/fes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0x69, 0xda, 0xf4, 0x7d, 0x33, 0x82, 0xe8, 0xe2, 0x61, 0x2d, 0x45, 0x4b, 0x2e, 0x06,
	0x0f, 0x1b, 0xd0, 0x8b, 0x27, 0xa5, 0x62, 0xc1, 0x73, 0xf0, 0xe4, 0x6d, 0x6b, 0x27, 0x6b, 0x68,
	0xf7, 0x0f, 0xd9, 0xad, 0x25, 0x9f, 0xd4, 0xaf, 0x23, 0xd9, 0x6d, 0x1b, 0x50, 0x28, 0x7a, 0x08,
	0x2c, 0x93, 0xe7, 0xd9, 0x9d, 0xdf, 0x0c, 0x9c, 0x9a, 0xa5, 0xc8, 0x4b, 0xb4, 0xed, 0xc7, 0x4c,
	0xad, 0x9d, 0x26, 0xe3, 0xb2, 0xb2, 0xb6, 0xd2, 0x8a, 0x6d, 0x74, 0xbd, 0x2c, 0x57, 0x7a, 0x63,
	0x19, 0x7e, 0xa0, 0x72, 0xd6, 0xe9, 0x1a, 0x47, 0x97, 0x42, 0x6b, 0xb1, 0xc2, 0xdc, 0xb3, 0xf3,
	0x75, 0x99, 0xbb, 0x4a, 0xa2, 0x75, 0x5c, 0x9a, 0xa0, 0x8f, 0xce, 0xbf, 0x03, 0x5c, 0x35, 0xe1,
	0x57, 0x9a, 0x43, 0x32, 0x15, 0xa2, 0x46, 0xc1, 0x1d, 0x92, 0x63, 0x88, 0xaa, 0x05, 0xed, 0x4d,
	0x7a, 0x59, 0x52, 0x44, 0xd5, 0x82, 0x10, 0x18, 0xb8, 0xc6, 0x20, 0x8d, 0x7c, 0xc5, 0x9f, 0xd3,
	0xcf, 0x08, 0xe2, 0x59, 0xfb, 0xf6, 0x6f, 0x68, 0x32, 0x83, 0x84, 0xef, 0xae, 0xa7, 0xfd, 0x49,
	0x2f, 0x3b, 0xba, 0xb9, 0x62, 0x87, 0xc2, 0xb0, 0x7d, 0x37, 0x45, 0x67, 0x92, 0x3b, 0x48, 0xf6,
	0x99, 0xe8, 0xc0, 0x5f, 0x33, 0x62, 0x21, 0x14, 0xdb, 0x85, 0x62, 0x2f, 0x3b, 0xa2, 0xe8, 0x60,
	0x92, 0xc1, 0x60, 0xc1, 0x1d, 0xa7, 0xb1, 0x97, 0xce, 0x7e, 0x48, 0x53, 0xd5, 0x14, 0x9e, 0x20,
	0x0f, 0x30, 0x34, 0xbc, 0x46, 0xe5, 0xe8, 0xf0, 0x6f, 0x7d, 0x6e, 0x35, 0x72, 0x0f, 0xf1, 0x7b,
	0xa5, 0x9c, 0xa5, 0xff, 0xbc, 0x9f, 0x1d, 0xf6, 0xfd, 0x0c, 0x9f, 0x5b, 0xbe, 0x08, 0x5a, 0x7a,
	0x0d, 0xd0, 0x15, 0xc9, 0x18, 0x92, 0x37, 0x2d, 0xcd, 0x0a, 0x1d, 0x86, 0x21, 0xff, 0x2f, 0xba,
	0x42, 0x7a, 0x01, 0xf0, 0xb4, 0x96, 0xb2, 0x09, 0x9b, 0x38, 0x81, 0xbe, 0xb4, 0x62, 0xbb, 0x8a,
	0xf6, 0xf8, 0x18, 0xbf, 0xf6, 0x4b, 0xb4, 0xf3, 0xa1, 0xcf, 0x79, 0xfb, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xdc, 0xbf, 0x40, 0x6a, 0x53, 0x02, 0x00, 0x00,
}
