package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// ApiserverSearchWorkflowResponse apiserver search workflow response
// swagger:model apiserverSearchWorkflowResponse
type ApiserverSearchWorkflowResponse struct {

	// workflows
	Workflows []string `json:"workflows,omitempty"`
}

// Validate validates this apiserver search workflow response
func (m *ApiserverSearchWorkflowResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkflows(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApiserverSearchWorkflowResponse) validateWorkflows(formats strfmt.Registry) error {

	if swag.IsZero(m.Workflows) { // not required
		return nil
	}

	return nil
}
