// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ApiserverWorkflowInvocationIdentifier apiserver workflow invocation identifier
// swagger:model apiserverWorkflowInvocationIdentifier
type ApiserverWorkflowInvocationIdentifier struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this apiserver workflow invocation identifier
func (m *ApiserverWorkflowInvocationIdentifier) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ApiserverWorkflowInvocationIdentifier) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApiserverWorkflowInvocationIdentifier) UnmarshalBinary(b []byte) error {
	var res ApiserverWorkflowInvocationIdentifier
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
