// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ApiserverSearchWorkflowResponse apiserver search workflow response
// swagger:model apiserverSearchWorkflowResponse
type ApiserverSearchWorkflowResponse struct {

	// workflows
	Workflows []string `json:"workflows"`
}

// Validate validates this apiserver search workflow response
func (m *ApiserverSearchWorkflowResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkflows(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApiserverSearchWorkflowResponse) validateWorkflows(formats strfmt.Registry) error {

	if swag.IsZero(m.Workflows) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApiserverSearchWorkflowResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApiserverSearchWorkflowResponse) UnmarshalBinary(b []byte) error {
	var res ApiserverSearchWorkflowResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
