// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ApiserverWorkflowInvocationList apiserver workflow invocation list
// swagger:model apiserverWorkflowInvocationList
type ApiserverWorkflowInvocationList struct {

	// invocations
	Invocations []string `json:"invocations"`
}

// Validate validates this apiserver workflow invocation list
func (m *ApiserverWorkflowInvocationList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInvocations(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApiserverWorkflowInvocationList) validateInvocations(formats strfmt.Registry) error {

	if swag.IsZero(m.Invocations) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApiserverWorkflowInvocationList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApiserverWorkflowInvocationList) UnmarshalBinary(b []byte) error {
	var res ApiserverWorkflowInvocationList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
