package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ProtobufEmpty service Foo {
//       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
//     }
//
// The JSON representation for `Empty` is empty JSON object `{}`.
// swagger:model protobufEmpty
type ProtobufEmpty interface{}
