package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// TaskDependencyParameters task dependency parameters
// swagger:model TaskDependencyParameters
type TaskDependencyParameters struct {

	// alias
	Alias string `json:"alias,omitempty"`

	// type
	Type TaskDependencyParametersDependencyType `json:"type,omitempty"`
}

// Validate validates this task dependency parameters
func (m *TaskDependencyParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskDependencyParameters) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.Validate(formats); err != nil {
		return err
	}

	return nil
}
