// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TaskInvocationSpecInputs Inputs contain all inputs to the task invocation
// swagger:model taskInvocationSpecInputs
type TaskInvocationSpecInputs map[string]TypedValue

// Validate validates this task invocation spec inputs
func (m TaskInvocationSpecInputs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", TaskInvocationSpecInputs(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
