// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TaskSpecRequires Dependencies for this task to execute
// swagger:model taskSpecRequires
type TaskSpecRequires map[string]TaskDependencyParameters

// Validate validates this task spec requires
func (m TaskSpecRequires) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", TaskSpecRequires(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
