// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TaskSpecInputs task spec inputs
// swagger:model taskSpecInputs
type TaskSpecInputs map[string]TypedValue

// Validate validates this task spec inputs
func (m TaskSpecInputs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", TaskSpecInputs(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
