// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// WorkflowInvocationStatusDynamicTasks In case the task ID also exists in the workflow spec, the dynamic task will be
// used as an overlay over the static task.
// swagger:model workflowInvocationStatusDynamicTasks
type WorkflowInvocationStatusDynamicTasks map[string]Task

// Validate validates this workflow invocation status dynamic tasks
func (m WorkflowInvocationStatusDynamicTasks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", WorkflowInvocationStatusDynamicTasks(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
