// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// WorkflowStatusTasks Tasks contains the status of the tasks, with the key being the task id.
// swagger:model workflowStatusTasks
type WorkflowStatusTasks map[string]TaskStatus

// Validate validates this workflow status tasks
func (m WorkflowStatusTasks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", WorkflowStatusTasks(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
