package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// WorkflowStatus Internal
// swagger:model WorkflowStatus
type WorkflowStatus struct {

	// error
	Error *Error `json:"error,omitempty"`

	// resolved tasks
	ResolvedTasks map[string]TaskTypeDef `json:"resolvedTasks,omitempty"`

	// status
	Status WorkflowStatusStatus `json:"status,omitempty"`

	// updated at
	UpdatedAt strfmt.DateTime `json:"updatedAt,omitempty"`
}

// Validate validates this workflow status
func (m *WorkflowStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResolvedTasks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowStatus) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {

		if err := m.Error.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

func (m *WorkflowStatus) validateResolvedTasks(formats strfmt.Registry) error {

	if swag.IsZero(m.ResolvedTasks) { // not required
		return nil
	}

	if err := validate.Required("resolvedTasks", "body", m.ResolvedTasks); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatus) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		return err
	}

	return nil
}
