// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WorkflowInvocationSpec Workflow Invocation Model
// swagger:model WorkflowInvocationSpec
type WorkflowInvocationSpec struct {

	// inputs
	Inputs WorkflowInvocationSpecInputs `json:"inputs,omitempty"`

	// ParentId contains the id of the encapsulating workflow invocation.
	//
	// This used within the workflow engine; for user-provided workflow invocations the parentId is ignored.
	ParentID string `json:"parentId,omitempty"`

	// workflow Id
	WorkflowID string `json:"workflowId,omitempty"`
}

// Validate validates this workflow invocation spec
func (m *WorkflowInvocationSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowInvocationSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowInvocationSpec) UnmarshalBinary(b []byte) error {
	var res WorkflowInvocationSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
