// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/scheduler/scheduler.proto

/*
Package scheduler is a generated protocol buffer package.

It is generated from these files:
	pkg/scheduler/scheduler.proto

It has these top-level messages:
	Schedule
	Action
	AbortAction
	InvokeTaskAction
	ScheduleRequest
*/
package scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/fission/fission-workflow/pkg/types"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ActionType contains all possible types of actions the scheduler can undertake.
//
// Each action can have a seperate datastructure defined here.
// Note about a RETURN/COMPLETE/FAIL action: The controller decides the final status of the workflow. In order to avoid
// inconsistencies in the replay.
type ActionType int32

const (
	// Invokes a task
	ActionType_INVOKE_TASK ActionType = 0
	// Abort cancels the invocation, leading to an ABORTED status.
	ActionType_ABORT ActionType = 1
)

var ActionType_name = map[int32]string{
	0: "INVOKE_TASK",
	1: "ABORT",
}
var ActionType_value = map[string]int32{
	"INVOKE_TASK": 0,
	"ABORT":       1,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}
func (ActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Schedule struct {
	InvocationId string                     `protobuf:"bytes,1,opt,name=invocationId" json:"invocationId,omitempty"`
	CreatedAt    *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=createdAt" json:"createdAt,omitempty"`
	Actions      []*Action                  `protobuf:"bytes,3,rep,name=actions" json:"actions,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Schedule) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *Schedule) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Schedule) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

// Action is the generic container of an action (signalled by ActionType) and the relevant message as a payload
type Action struct {
	Type    ActionType            `protobuf:"varint,1,opt,name=type,enum=ActionType" json:"type,omitempty"`
	Payload *google_protobuf1.Any `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Action) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return ActionType_INVOKE_TASK
}

func (m *Action) GetPayload() *google_protobuf1.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type AbortAction struct {
	Reason string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
}

func (m *AbortAction) Reset()                    { *m = AbortAction{} }
func (m *AbortAction) String() string            { return proto.CompactTextString(m) }
func (*AbortAction) ProtoMessage()               {}
func (*AbortAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AbortAction) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type InvokeTaskAction struct {
	// Id of the task in the workflow
	Id     string                       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Inputs map[string]*types.TypedValue `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *InvokeTaskAction) Reset()                    { *m = InvokeTaskAction{} }
func (m *InvokeTaskAction) String() string            { return proto.CompactTextString(m) }
func (*InvokeTaskAction) ProtoMessage()               {}
func (*InvokeTaskAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InvokeTaskAction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InvokeTaskAction) GetInputs() map[string]*types.TypedValue {
	if m != nil {
		return m.Inputs
	}
	return nil
}

type ScheduleRequest struct {
	Workflow   *types.Workflow           `protobuf:"bytes,1,opt,name=workflow" json:"workflow,omitempty"`
	Invocation *types.WorkflowInvocation `protobuf:"bytes,2,opt,name=invocation" json:"invocation,omitempty"`
}

func (m *ScheduleRequest) Reset()                    { *m = ScheduleRequest{} }
func (m *ScheduleRequest) String() string            { return proto.CompactTextString(m) }
func (*ScheduleRequest) ProtoMessage()               {}
func (*ScheduleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ScheduleRequest) GetWorkflow() *types.Workflow {
	if m != nil {
		return m.Workflow
	}
	return nil
}

func (m *ScheduleRequest) GetInvocation() *types.WorkflowInvocation {
	if m != nil {
		return m.Invocation
	}
	return nil
}

func init() {
	proto.RegisterType((*Schedule)(nil), "Schedule")
	proto.RegisterType((*Action)(nil), "Action")
	proto.RegisterType((*AbortAction)(nil), "AbortAction")
	proto.RegisterType((*InvokeTaskAction)(nil), "InvokeTaskAction")
	proto.RegisterType((*ScheduleRequest)(nil), "ScheduleRequest")
	proto.RegisterEnum("ActionType", ActionType_name, ActionType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scheduler service

type SchedulerClient interface {
	Evaluate(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*Schedule, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) Evaluate(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := grpc.Invoke(ctx, "/Scheduler/evaluate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scheduler service

type SchedulerServer interface {
	Evaluate(context.Context, *ScheduleRequest) (*Schedule, error)
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Scheduler/Evaluate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Evaluate(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "evaluate",
			Handler:    _Scheduler_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/scheduler/scheduler.proto",
}

func init() { proto.RegisterFile("pkg/scheduler/scheduler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xd1, 0x6a, 0x9c, 0x40,
	0x14, 0x8d, 0x26, 0xd9, 0x5d, 0xaf, 0x25, 0x91, 0x69, 0x29, 0x76, 0x21, 0x64, 0x23, 0x04, 0xb6,
	0x85, 0x8e, 0x60, 0x68, 0x49, 0xfb, 0x66, 0x21, 0x05, 0x09, 0x34, 0x30, 0x91, 0x94, 0x3e, 0x95,
	0x59, 0x9d, 0xdd, 0x88, 0xae, 0x63, 0x9d, 0x71, 0x83, 0xdf, 0xd0, 0xaf, 0xe8, 0x9f, 0x16, 0x75,
	0x66, 0x37, 0xdd, 0xbe, 0xe8, 0xdc, 0x73, 0xce, 0x1c, 0xcf, 0xbd, 0x57, 0x38, 0xab, 0xf2, 0x95,
	0x2f, 0x92, 0x47, 0x96, 0x36, 0x05, 0xab, 0x77, 0x27, 0x5c, 0xd5, 0x5c, 0xf2, 0xe9, 0xa7, 0x55,
	0x26, 0x1f, 0x9b, 0x05, 0x4e, 0xf8, 0xda, 0x5f, 0x66, 0x42, 0x64, 0xbc, 0xd4, 0xef, 0xf7, 0x4f,
	0xbc, 0xce, 0x97, 0x05, 0x7f, 0xf2, 0x3b, 0x0b, 0xd9, 0x56, 0x4c, 0x0c, 0x4f, 0x75, 0xf5, 0x7c,
	0xc5, 0xf9, 0xaa, 0x60, 0x7e, 0x5f, 0x2d, 0x9a, 0xa5, 0x2f, 0xb3, 0x35, 0x13, 0x92, 0xae, 0x2b,
	0x25, 0x78, 0xb3, 0x2f, 0xa0, 0x65, 0x3b, 0x50, 0xde, 0x6f, 0x03, 0x26, 0xf7, 0x2a, 0x0a, 0xf2,
	0xe0, 0x45, 0x56, 0x6e, 0x78, 0x42, 0x65, 0xc6, 0xcb, 0x28, 0x75, 0x8d, 0x99, 0x31, 0xb7, 0xc8,
	0x3f, 0x18, 0xba, 0x06, 0x2b, 0xa9, 0x19, 0x95, 0x2c, 0x0d, 0xa5, 0x6b, 0xce, 0x8c, 0xb9, 0x1d,
	0x4c, 0xf1, 0xe0, 0x8f, 0xb5, 0x3f, 0x8e, 0x75, 0x00, 0xb2, 0x13, 0xa3, 0x0b, 0x18, 0xd3, 0xa4,
	0x73, 0x11, 0xee, 0xe1, 0xec, 0x70, 0x6e, 0x07, 0x63, 0x1c, 0xf6, 0x35, 0xd1, 0xb8, 0xf7, 0x03,
	0x46, 0x03, 0x84, 0xce, 0xe1, 0xa8, 0x6b, 0xb1, 0x8f, 0x70, 0x12, 0xd8, 0x4a, 0x19, 0xb7, 0x15,
	0x23, 0x3d, 0x81, 0x30, 0x8c, 0x2b, 0xda, 0x16, 0x9c, 0xa6, 0xee, 0x51, 0x9f, 0xe2, 0xd5, 0x7f,
	0x29, 0xc2, 0xb2, 0x25, 0x5a, 0xe4, 0x5d, 0x82, 0x1d, 0x2e, 0x78, 0x2d, 0x95, 0xff, 0x6b, 0x18,
	0xd5, 0x8c, 0x0a, 0x5e, 0xaa, 0x26, 0x55, 0xe5, 0xfd, 0x31, 0xc0, 0x89, 0xca, 0x0d, 0xcf, 0x59,
	0x4c, 0x45, 0xae, 0xc4, 0x27, 0x60, 0x66, 0x7a, 0x1a, 0x66, 0x96, 0xa2, 0x0f, 0x30, 0xca, 0xca,
	0xaa, 0x91, 0xc2, 0x35, 0xfb, 0x46, 0xce, 0xf0, 0xfe, 0x15, 0x1c, 0xf5, 0xfc, 0x4d, 0x29, 0xeb,
	0x96, 0x28, 0xf1, 0xf4, 0x2b, 0xd8, 0xcf, 0x60, 0xe4, 0xc0, 0x61, 0xce, 0x5a, 0x65, 0xdb, 0x1d,
	0xd1, 0x05, 0x1c, 0x6f, 0x68, 0xd1, 0x30, 0x35, 0x57, 0x1b, 0x77, 0xfd, 0xa6, 0x0f, 0x1d, 0x44,
	0x06, 0xe6, 0xb3, 0x79, 0x6d, 0x78, 0x6b, 0x38, 0xd5, 0x2b, 0x23, 0xec, 0x57, 0xc3, 0x84, 0x44,
	0x97, 0x30, 0xd1, 0x3f, 0x49, 0x6f, 0x68, 0x07, 0x16, 0xfe, 0xae, 0x00, 0xb2, 0xa5, 0xd0, 0x15,
	0xc0, 0x6e, 0x99, 0xea, 0x2b, 0x2f, 0xb7, 0xc2, 0x68, 0x4b, 0x91, 0x67, 0xb2, 0x77, 0x73, 0x80,
	0xdd, 0xf4, 0xd1, 0x29, 0xd8, 0xd1, 0xb7, 0x87, 0xbb, 0xdb, 0x9b, 0x9f, 0x71, 0x78, 0x7f, 0xeb,
	0x1c, 0x20, 0x0b, 0x8e, 0xc3, 0x2f, 0x77, 0x24, 0x76, 0x8c, 0xe0, 0x23, 0x58, 0x3a, 0x58, 0x8d,
	0xde, 0xc2, 0x84, 0x75, 0x99, 0xa9, 0x64, 0xc8, 0xc1, 0x7b, 0x81, 0xa7, 0xd6, 0x16, 0xf1, 0x0e,
	0x16, 0xa3, 0x7e, 0x65, 0x57, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x1b, 0xe3, 0x85, 0x23,
	0x03, 0x00, 0x00,
}
