// Code generated by go-swagger; DO NOT EDIT.

package workflow_invocation_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// NewInvokeSyncParams creates a new InvokeSyncParams object
// with the default values initialized.
func NewInvokeSyncParams() *InvokeSyncParams {
	var ()
	return &InvokeSyncParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInvokeSyncParamsWithTimeout creates a new InvokeSyncParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInvokeSyncParamsWithTimeout(timeout time.Duration) *InvokeSyncParams {
	var ()
	return &InvokeSyncParams{

		timeout: timeout,
	}
}

// NewInvokeSyncParamsWithContext creates a new InvokeSyncParams object
// with the default values initialized, and the ability to set a context for a request
func NewInvokeSyncParamsWithContext(ctx context.Context) *InvokeSyncParams {
	var ()
	return &InvokeSyncParams{

		Context: ctx,
	}
}

// NewInvokeSyncParamsWithHTTPClient creates a new InvokeSyncParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInvokeSyncParamsWithHTTPClient(client *http.Client) *InvokeSyncParams {
	var ()
	return &InvokeSyncParams{
		HTTPClient: client,
	}
}

/*InvokeSyncParams contains all the parameters to send to the API endpoint
for the invoke sync operation typically these are written to a http.Request
*/
type InvokeSyncParams struct {

	/*Body*/
	Body *models.WorkflowInvocationSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the invoke sync params
func (o *InvokeSyncParams) WithTimeout(timeout time.Duration) *InvokeSyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the invoke sync params
func (o *InvokeSyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the invoke sync params
func (o *InvokeSyncParams) WithContext(ctx context.Context) *InvokeSyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the invoke sync params
func (o *InvokeSyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the invoke sync params
func (o *InvokeSyncParams) WithHTTPClient(client *http.Client) *InvokeSyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the invoke sync params
func (o *InvokeSyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the invoke sync params
func (o *InvokeSyncParams) WithBody(body *models.WorkflowInvocationSpec) *InvokeSyncParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the invoke sync params
func (o *InvokeSyncParams) SetBody(body *models.WorkflowInvocationSpec) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *InvokeSyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
