// Code generated by go-swagger; DO NOT EDIT.

package workflow_invocation_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// WfiListReader is a Reader for the WfiList structure.
type WfiListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WfiListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWfiListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWfiListOK creates a WfiListOK with default headers values
func NewWfiListOK() *WfiListOK {
	return &WfiListOK{}
}

/*WfiListOK handles this case with default header values.

WfiListOK wfi list o k
*/
type WfiListOK struct {
	Payload *models.ApiserverWorkflowInvocationList
}

func (o *WfiListOK) Error() string {
	return fmt.Sprintf("[GET /invocation][%d] wfiListOK  %+v", 200, o.Payload)
}

func (o *WfiListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverWorkflowInvocationList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
