// Code generated by go-swagger; DO NOT EDIT.

package workflow_invocation_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// WfiGetReader is a Reader for the WfiGet structure.
type WfiGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WfiGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWfiGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWfiGetOK creates a WfiGetOK with default headers values
func NewWfiGetOK() *WfiGetOK {
	return &WfiGetOK{}
}

/*WfiGetOK handles this case with default header values.

WfiGetOK wfi get o k
*/
type WfiGetOK struct {
	Payload *models.WorkflowInvocation
}

func (o *WfiGetOK) Error() string {
	return fmt.Sprintf("[GET /invocation/{id}][%d] wfiGetOK  %+v", 200, o.Payload)
}

func (o *WfiGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WorkflowInvocation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
