// Code generated by go-swagger; DO NOT EDIT.

package workflow_invocation_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fission/fission-workflows/cmd/wfcli/swagger-client/models"
)

// NewWfiValidateParams creates a new WfiValidateParams object
// with the default values initialized.
func NewWfiValidateParams() *WfiValidateParams {
	var ()
	return &WfiValidateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWfiValidateParamsWithTimeout creates a new WfiValidateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWfiValidateParamsWithTimeout(timeout time.Duration) *WfiValidateParams {
	var ()
	return &WfiValidateParams{

		timeout: timeout,
	}
}

// NewWfiValidateParamsWithContext creates a new WfiValidateParams object
// with the default values initialized, and the ability to set a context for a request
func NewWfiValidateParamsWithContext(ctx context.Context) *WfiValidateParams {
	var ()
	return &WfiValidateParams{

		Context: ctx,
	}
}

// NewWfiValidateParamsWithHTTPClient creates a new WfiValidateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWfiValidateParamsWithHTTPClient(client *http.Client) *WfiValidateParams {
	var ()
	return &WfiValidateParams{
		HTTPClient: client,
	}
}

/*WfiValidateParams contains all the parameters to send to the API endpoint
for the wfi validate operation typically these are written to a http.Request
*/
type WfiValidateParams struct {

	/*Body*/
	Body *models.WorkflowInvocationSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the wfi validate params
func (o *WfiValidateParams) WithTimeout(timeout time.Duration) *WfiValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the wfi validate params
func (o *WfiValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the wfi validate params
func (o *WfiValidateParams) WithContext(ctx context.Context) *WfiValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the wfi validate params
func (o *WfiValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the wfi validate params
func (o *WfiValidateParams) WithHTTPClient(client *http.Client) *WfiValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the wfi validate params
func (o *WfiValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the wfi validate params
func (o *WfiValidateParams) WithBody(body *models.WorkflowInvocationSpec) *WfiValidateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the wfi validate params
func (o *WfiValidateParams) SetBody(body *models.WorkflowInvocationSpec) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *WfiValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
