// Code generated by go-swagger; DO NOT EDIT.

package workflow_invocation_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWfiListParams creates a new WfiListParams object
// with the default values initialized.
func NewWfiListParams() *WfiListParams {

	return &WfiListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWfiListParamsWithTimeout creates a new WfiListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWfiListParamsWithTimeout(timeout time.Duration) *WfiListParams {

	return &WfiListParams{

		timeout: timeout,
	}
}

// NewWfiListParamsWithContext creates a new WfiListParams object
// with the default values initialized, and the ability to set a context for a request
func NewWfiListParamsWithContext(ctx context.Context) *WfiListParams {

	return &WfiListParams{

		Context: ctx,
	}
}

// NewWfiListParamsWithHTTPClient creates a new WfiListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWfiListParamsWithHTTPClient(client *http.Client) *WfiListParams {

	return &WfiListParams{
		HTTPClient: client,
	}
}

/*WfiListParams contains all the parameters to send to the API endpoint
for the wfi list operation typically these are written to a http.Request
*/
type WfiListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the wfi list params
func (o *WfiListParams) WithTimeout(timeout time.Duration) *WfiListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the wfi list params
func (o *WfiListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the wfi list params
func (o *WfiListParams) WithContext(ctx context.Context) *WfiListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the wfi list params
func (o *WfiListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the wfi list params
func (o *WfiListParams) WithHTTPClient(client *http.Client) *WfiListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the wfi list params
func (o *WfiListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *WfiListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
