// Code generated by go-swagger; DO NOT EDIT.

package workflow_invocation_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new workflow invocation api API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for workflow invocation api API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
Cancel cancels a workflow invocation

This action is irreverisble. A canceled invocation cannot be resumed or restarted.
In case that an invocation already is canceled, has failed or has completed, nothing happens.
In case that an invocation does not exist a HTTP 404 error status is returned.
*/
func (a *Client) Cancel(params *CancelParams) (*CancelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCancelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Cancel",
		Method:             "DELETE",
		PathPattern:        "/invocation/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CancelReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CancelOK), nil

}

/*
Invoke creates a new workflow invocation

In case the invocation specification is missing fields or contains invalid fields, a HTTP 400 is returned.
*/
func (a *Client) Invoke(params *InvokeParams) (*InvokeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInvokeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Invoke",
		Method:             "POST",
		PathPattern:        "/invocation",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &InvokeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*InvokeOK), nil

}

/*
InvokeSync invoke sync API
*/
func (a *Client) InvokeSync(params *InvokeSyncParams) (*InvokeSyncOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInvokeSyncParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "InvokeSync",
		Method:             "POST",
		PathPattern:        "/invocation/sync",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &InvokeSyncReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*InvokeSyncOK), nil

}

/*
InvokeSync2 invoke sync2 API
*/
func (a *Client) InvokeSync2(params *InvokeSync2Params) (*InvokeSync2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInvokeSync2Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "InvokeSync2",
		Method:             "GET",
		PathPattern:        "/invocation/sync",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &InvokeSync2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*InvokeSync2OK), nil

}

/*
WfiGet gets the specification and status of a workflow invocation

Get returns three different aspects of the workflow invocation, namely the spec (specification), status and logs.
To lighten the request load, consider using a more specific request.
*/
func (a *Client) WfiGet(params *WfiGetParams) (*WfiGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWfiGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "WfiGet",
		Method:             "GET",
		PathPattern:        "/invocation/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &WfiGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*WfiGetOK), nil

}

/*
WfiList wfi list API
*/
func (a *Client) WfiList(params *WfiListParams) (*WfiListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWfiListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "WfiList",
		Method:             "GET",
		PathPattern:        "/invocation",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &WfiListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*WfiListOK), nil

}

/*
WfiValidate wfi validate API
*/
func (a *Client) WfiValidate(params *WfiValidateParams) (*WfiValidateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWfiValidateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "WfiValidate",
		Method:             "POST",
		PathPattern:        "/invocation/validate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &WfiValidateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*WfiValidateOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
