// Code generated by hack/codegen-version.sh. DO NOT EDIT.
package version

import "time"

const (
	dateFormat string = time.RFC1123Z

	// Git commit (e.g. 1b4716ab84903b2e477135a3dc5afdb07f685cb7)
	GitCommit string = "75c8e3a498cb5f1928275ab901031f74baaf05b9"

	// Version contains a (potentially) human-readable version
	// For example 1.1.0 or 1b4716ab84903b2e477135a3dc5afdb07f685cb7
	Version string = "75c8e3a498cb5f1928275ab901031f74baaf05b9"

	// gitDate is a date in RFC1123Z format
	gitDate string = "Tue, 24 Jul 2018 21:35:17 +0200"
)

var (
	GitDate time.Time
)

func init() {

	d, err := time.Parse(dateFormat, gitDate)
	if err != nil {
		panic(err)
	}
	GitDate = d
}
