// Code generated by hack/codegen-version.sh. DO NOT EDIT.
package version

import "time"

const (
	dateFormat string = time.RFC1123Z

	// Git commit (e.g. 1b4716ab84903b2e477135a3dc5afdb07f685cb7)
	GitCommit string = "6ae991e3b4c17ebbe3b323fb163514c264960cbd"

	// Version contains a (potentially) human-readable version
	// For example 1.1.0 or 1b4716ab84903b2e477135a3dc5afdb07f685cb7
	Version string = "0.4.0"

	// gitDate is a date in RFC1123Z format
	gitDate string = "Wed, 06 Jun 2018 10:20:28 +0200"
)

var (
	GitDate time.Time
)

func init() {

	d, err := time.Parse(dateFormat, gitDate)
	if err != nil {
		panic(err)
	}
	GitDate = d
}
